<$ROOT/mkconfig

TARG=0a

OFILES=\
	y.tab.$O\
	lex.$O\

HFILES=\
	../vc/v.out.h\
	y.tab.h\
	a.h\

YFILES=	a.y\

LIBS=cc bio 9		# order is important


<$ROOT/mkfiles/mkone-$SHELLTYPE

YFLAGS=-D1 -d
CFLAGS=	$CFLAGS -I../include

lex.$O:	../cc/macbody ../cc/lexbody

$OBJDIR/liblibcc.a:
	cd ../cc
	mk $MKFLAGS install
	mk $MKFLAGS clean
