#uncomment following line for full Microsoft debug symbols
#LDEBUG=-debug -debugtype:cv -pdb:none
<$ROOT/mkconfig
SYSTARG=Nt
SYSHOST=Nt
OBJTYPE=386
OBJDIR=$SYSTARG/$OBJTYPE
<$OBJDIR/../mkfile
<$OBJDIR/mkfile

TARG=ntsrv

OFILES=	ntsrv.$O\

HFILES=

LIBS=9

CFLAGS=$CFLAGS -I.


SYSLIBS=	$SYSLIBS wsock32.lib user32.lib gdi32.lib advapi32.lib winmm.lib mpr.lib

<$ROOT/mkfiles/mkone-$SHELLTYPE
