= {name}: one hell of an operating system
:docpath: https://inf.bryton.io/manual
:name: inf

{docpath}[{name}] is a derivative of http://www.inferno-os.info/inferno/[Inferno] (a distributed operating system originally developed at http://www.bell-labs.com/[Bell Labs] and currently maintained by http://www.vitanuova.com/[Vita Nuova]) aimed at modernization for mass adoption.

WARNING: {name} is not ready for production use.

Applications are written in {docpath}/limbo[limbo] and compiled for {docpath}/dis[dis] to run anywhere on a network in a portable operating system.

The design has three principles:

 .  All resources are named and accessed as files.
 .  One protocol ({docpath}/9p[9p]) allows uniform access to these resources.
 .  A single local namespace joins resources provided by remote services.

In this manner, programs can access resources using only the file operations `open`, `read`, `write`, and `close`.

NOTE: That is to say, networked participants only need to communicate with 9p instead of http(s)/dav, smtp, imap/pop, ssh/scp, ftp, ssl/tls, smb, ntp, ppp, ldap, dhcp, dns, sip, ...


The following system/architecture pairs are supported:

[cols="s,9*^"]
|===
|             | 386 |amd64| arm |68020| mips|power|sparc| spim|thumb

|DragonFlyBSD |  x  |     |     |     |     |     |     |     |
|FreeBSD      |  x  |     |     |     |     |     |     |     |
|HP/UX        |     |     |     |     |  o  |     |     |     |
|Irix         |     |     |     |     |  x  |     |     |     |
|Inferno      |  x  |     |  x  |     |  x  |  x  |  x  |  x  |  x
|Linux        |  x  |     |  x  |     |     |  x  |     |  x  |
|MacOSX       |  x  |     |     |     |     |  x  |     |     |
|NetBSD       |  x  |     |     |     |     |     |     |     |
|Plan 9       |  x  |  x  |  x  |  x  |  x  |  x  |  x  |     |
|Solaris      |  o  |     |     |     |     |     |  x  |     |
|Unixware     |  x  |     |     |     |     |     |     |     |
|Windows      |  x  |     |     |     |     |     |     |     |
|===

//Dependencies:

//32bit: gcc, x11, x

To install

 . edit link:mkconfig[`mkconfig`]
 . execute link:makemk.sh[`makemk.sh`] to build {docpath}/mk[`mk`].
 . set `PATH` to include the `$ROOT/arch/$OBJTYPE/$SYSTARG/bin/` directory.
 . run `mk install`

This will create and install the libraries, limbo compiler, emu (if running hosted), and auxiliary commands.

Now execute `emu` and you should see the {docpath}/sh[`sh`] prompt awaiting your input:

    ;

Documentation is at {docpath}[].

== about

https://gitlab.com/hall/inf[`{name}`] is licensed under the [GNU GPLv3](LICENSE).

