objtype=mips
OBJTYPE=$objtype
<$ROOT/mkconfig

LIB=libsec.a
FILES=\
	md5block\
	sha1block\

HFILES=$ROOT/include/libsec.h

SFILES=${FILES:%=%.s}

OFILES=${FILES:%=%.$O}

<$ROOT/mkfiles/mksyslib-$SHELLTYPE
