= chmod: change file mode (permissions)


*chmod* _mode_ _file ..._


_Chmod_ changes the mode (permissions) of each _file_ according to
_mode_, which may be an octal number or a symbolic change to the
existing mode.

A _mode_ can be numerically formed as the

of the following octal values (a leading *8r* is ignored):

0400::
  read by owner
0200::
  write by owner
0100::
  execute (search in directory) by owner
0070::
  read, write, execute (search) by group
0007::
  read, write, execute (search) by others

A symbolic _mode_ has the form:

_______________________
[_who_] _op permission_
_______________________

The _who_ part is a combination of the letters *u* (for user's
permissions), *g* (group) and *o* (other). The letter *a* stands for
*ugo*. If _who_ is omitted, the default is *a*.

The _op_ field can be: *+* to add _permission_ to the file's mode, *-*
to take away _permission_, *=* to assign _permission_ absolutely (all
other bits being reset).

The _permission_ field is any combination of the letters *r* (read), *w*
(write), *x* (execute), *a* (append only), *l* (exclusive access), and
*t* (temporary, not archived).

== SOURCE

*/appl/cmd/chmod.b*

== SEE ALSO

_chgrp_(1), _ls_(1), _sys-stat_(2)

== BUGS

The interpretation of the modes is limited on some host operating
systems, particularly variants of Windows.
