= cook: SGML converter


*cook* [ *-f* _format_ ] [ *-o* _outfile_ ] [ _infile_ ]


*Cook* reads a file in SGML format and produces an interpretation of the
file in either LaTex or HTML format on standard output.

If no _infile_ argument is present, the standard input is read. If an
_outfile_ argument is present, the results are written to that file
instead of standard output. The _format_ argument must be either *html*
to produce HTML format output or one of: *latex*, *latexbook*,
*latexpart*, *latexproc*, or *latexslides* to produce LaTex output.

The *latexpart* format assumes that the resulting output is to be
included in the body of a controlling LaTex document. The other LaTex
format options result in the generation of various LaTex wrapping
commands.

*Cook* was designed to operate on the output of the *Brutus* editor (See
_brutus_(1) ) and so its mapping of SGML tags is closely linked to those
generated by _brutus_.

The following tags are recognised: *Author*, **Bold.**__n__, *Caption*,
*Example*, *Exercise*, *Extension*, *Float*, *Heading*, *Index*,
*Index-topic*, **Italic.**__n__, *Label*, *Label-ref*, *List*,
*List-elem*, *No-fill*, *Par*, **Roman.**__n__, *SGML*, *Title*, and
**Type.**__n__, where _n_ is a character point size and must be one of:
*6*, *8*, *10*, *12* or *16*.

== FILES

*/dis/wm/brutus/*

== SOURCE

*/appl/cmd/cook.b*

== SEE ALSO

_brutus_(1)

== DIAGNOSTICS

*Not an SGML file*: The first line of the input file must contain the
SGML tag *<SGML>* and nothing else.
