= fs: file-hierarchy traversal


*fs* _verb arg_

 +


*Fs* evaluates an expression whose values represent the contents of a
hierarchical filesystem. There are six types of value:

*fs*::
  The complete contents of a filesystem.
*entries*::
  Information about the entries in a filesystem without their content.
*gate*::
  A condition that can be used with conditional verbs. A gate is open to
  entries satisfying particular criteria.
*selector*::
  A comparator which compares two entries and selects one, both or
  neither of them.
*string*::
  A simple string literal, represented by itself, or quoted according to
  the usual shell quoting rules.
*command*::
  A shell command, represented by an ``**@**'' character followed by a
  braced block containing the shell commands.
*void*::
  No value. An expression of this type cannot be used as an argument to
  any verb.

A value is represented either by a literal (a string or shell command),
or by a braced block, **\{**__verb__ [_arg_...]}, whose value is the
result of evaluating _verb_ with the given arguments.

In the following description of the verbs provided, an entry such as:

*print _entries_ -> void*::

describes a verb *print*, which takes one argument of type _entries_,
and the result of which is of type *void*. If the type is not one of
those described above, it should be taken to be of type _string_.

With no arguments, _fs_ prints a summary of the available verbs. Verbs
understood by _fs_ include:

and _gate gate_ [_gate_...] -> _gate_::
  *And* is a gate that is open to an entry if all its arguments are
  open.
bundle _fs_ -> _void_::
  *Bundle* converts _fs_ to an archival format and writes it to the
  standard output.
compose [-d] _op_ -> _selector_::
  *Compose* implements ``compositing''-style operators, useful when
  merging filesystems. _Op_ specifies the operator, taking its name from
  the graphical Porter-Duff equivalent: *AinB*, *AinB*, *BinA*, *AoutB*,
  *BoutA*, *A*, *AoverB*, *AatopB*, *AxorB*, *B*, *BoverA*, or *BatopA.*
  For instance, *AinB* gives the intersection of A and B; *AatopB* gives
  A whereever both A and B exist, and B otherwise. When used as a
  selector for *merge*, operators that exclude the union of A and B are
  not very useful, as they will exclude all common directories at the
  top level. Given the *-d* option, compose will allow through
  directories that would otherwise be excluded in this way, making
  operators such as *AxorB* (all that A does not hold in common with B)
  more useful, although accurate only for regular files.
depth _n_ -> _gate_::
  *Depth* is a gate open only to entries which are within _n_ levels of
  the root of the filesystem.
entries _fs_ -> _entries_::
  *Entries* produces all the entries contained within _fs_.
eval _expr_ -> _any_::
  *Eval* evaluates an _fs_ expression and yields its result.
filter [-d]_gate fs_ -> _fs_::
  The result of *filter* is a filesystem from which all entries that
  will not pass through _gate_, and their descendents, have been
  removed. If the *-d* flag is given, only files are filtered -
  directories bypass the gate.
ls [-um] _entries_ -> _void_::
  Print each entry in the style of *ls -l* (see _ls_(1)). If the *-u*
  flag is given, the file access time rather than the file modification
  time will be printed. If the *-m* flag is given, the name of the user
  that last modified the file is printed too.
exec [-pP] [-t _command_] [-n _n_] _command entries_ -> _void_::
  Run its argument _command_ for each entry in _entries ._ If the *-n*
  flag is specified, *exec* will try to gather _n_ entries together
  before invoking the command (default 1). The environent variable
  *$file* is set to the names of the entries that have been gathered. If
  the *-p* flag is given, environment variables are set giving
  information about the mode, owner, modification time and size of the
  entry (they are named after the equivalent field names in the *Dir*
  structure; see _sys-stat_(2)). This option is only valid when _n_ is
  1. The *-P* flag causes all the other fields in the Dir structure to
  be included too. Note that the command is run in the same shell
  context each time, so environment variable set on one execution can be
  retrieved on the next. The *-t* flag can be used to specify a command
  which will be executed just before termination.
match [-ar] _pattern_ -> _gate_::
  *Match* is a gate that is open if the entry's filename matches the
  _pattern_. If the *-a* flag is given, the whole path will be used for
  the match. If *-r* is specified, the pattern is evaluated as a regular
  expression, otherwise it is a shell-style pattern in the style of
  _filepat_(2).
merge [-1] [-c _selector_] _fs fs_ [_fs_...] -> _fs_::
  Recursively merge the contents of its argument filesystems. _Selector_
  is consulted to see which entries are chosen for the result; if not
  given, entries are resolved in favour of the first filesystem
  (equivalent to *\{compose AoverB}*). If the *-1* flag is given,
  merging takes place only in the top-level directory.
mode _spec_ -> _gate_::
  *Mode* is a gate that lets through entries whose file permissions
  satisfy _spec_, which is a string in the style of _chmod_(1). If the
  _op_ field is *+*, the specified permissions must be present; if *-*,
  they must be absent, and if *=*, they must be exactly as given. The
  directory and auth modes are specified with the characters ``d'' and
  ``A'' respectively.
not _gate_ -> _gate_::
  *Not* is a gate open to an entry if its argument is not.
or _gate gate_ [_gate_...] -> _gate_::
  *Or* is a gate open to an entry if any argument is open.
path [-x] _path_... -> _gate_::
  *Path* is a gate open to an entry whose full pathname is an ancestor
  or a descendent of any _path._ If *-x* is specified, the gate is open
  to any path _except_ descendents of the paths given.
pipe [-1pP] _command fs_ -> _void_::
  *Pipe* is similar to exec, except that the contents of all files in
  _fs_ are piped through _command_. Unless the *-1* option is given,
  _command_ is started once for each file, with *$file* set to its name,
  and other environment variables set according to the *-p* or *-P*
  options, as for *exec*. If the *-1* option is specified, _command_ is
  started once only - all file data is piped through that.
print _entries_ -> _void_::
  Print the path name of each entry.
proto [-r _root_] _protofile_ -> _fs_::
  Evaluate _protofile_ as a _mkfs_(8) _proto_ file. If _root_ is
  specified, it will be used as the root of the resulting _fs_.
query _command_ -> _gate_::
  *Query* is a gate that runs _command_ to determine whether it is open:
  an empty exit status from the command yields an open gate. The
  environment variable *$file* is set for the command to the path name
  of the entry that is being queried for.
run _command_ -> _string_::
  *Run* runs _command_ and substitutes the value of the environment
  variable *$s* after its invocation. *$s* must have exactly one
  element.
select _gate entries_ -> _entries_::
  Select only those entries within _entries_ that will pass through
  _gate_. Descendents of elided entries are not affected.
setroot [-c] _path_ _fs_ -> _fs_::
  *Setroot* sets the name of the root directory of _fs_. If the *-c*
  flag is given, the elements in the root directory will be made
  explicit in the hierarchy (i.e. the name of the top directory will not
  contain any */* characters).
size _entries_ -> _void_::
  Print the sum of the size of all entries, in bytes.
unbundle _file_ -> _fs_::
  *Unbundle* reads an archive as produced by *bundle* from _file_; its
  result is the contents of the filesystem that was originally bundled.
  If _file_ is __``__**-**_'',_ the standard input is read.
walk _path_ -> _fs_::
  *Walk* produces a filesystem that's the result of traversing all the
  files and directories underneath _path_.
write _dir fs_ -> _void_::
  Write the contents of _fs_ to the filesystem rooted at _dir ._ If
  _dir_ is empty, _fs_ will be written to the root directory originally
  associated with fs.

As a convenience, _fs_ carries out some automatic type conversions
(conversions are applied recursively, so for instance, an *fs*-valued
expression at the top level will converted to void by applying *\{print
\{entries* __fs__**}}.**

*string*->*fs*::
  The result is \{walk _string_}_._
*fs*->*entries*::
  The result is \{entries__ fs__}_._
*string*->*gate*::
  The result is \{match__ string__}_._
*entries*->*void*::
  The result is \{print__ entries__}_._
*command*->*string*::
  The result is \{run__ command__}_._

== EXAMPLES

Print the size of all files below the current directory:

....
	fs size .
....

Show the names of all files in x that aren't in y:

....
	fs select {mode -d} {merge -c {compose -d AoutB} x y}
....

Remove all files from /appl ending in *.dis*:

....
	fs exec @{rm $file} {select *.dis /appl}
....

Recursively copy the current directory to */tmp/foo*.

....
	fs bundle . | fs write /tmp/foo {unbundle -}
....

A simpler method of the above:

....
	fs write /tmp/foo .
....

Interactively remove all regular files from one level of the current
directory:

....
fs exec @{rm $file} {select {query
	@{echo -n $file:; ~ `{read} y yes}}
	{select {mode -d} {filter {depth 1} .}}}
....

Create a new archive containing those files from below the current
directory that were held in an old archive:

....
	fs bundle {merge -c {compose AinB} . {unbundle old.bundle}} > new.bundle
....

== SOURCE

*/appl/cmd/fs.b* +
*/appl/cmd/fs/*.b* +
*/appl/lib/fslib.b*

== SEE ALSO

_sh_(1)
