= idea: encrypt/decrypt a file with the IDEA cipher


*idea* [ *-e* ] [ *-d* ] _key_ [ _datafile_ ]


_Idea_ encrypts or decrypts data using the IDEA (International Data
Encryption Algorithm) cipher first proposed by Xuejia Lai and James
Massey in 1990.

The *-e* option encrypts the data and the *-d* option decrypts the data.
Exactly one of these must be specified on the command line.

The _key_ is any 16 character string which is used as the key for both
encryption and decryption.

The data to be encrypted/decrypted is either in _datafile_ or is read
from standard input. If no input file is given, the output from _idea_
is always sent to standard output. For encryption, if an input file is
specified the output is sent to a file with the name _datafile.id._ For
decryption, if an input file is specified it should have a .id extension
and the output is sent to a file whose name is that of _datafile_
without the .id extension.

== EXAMPLES

Encrypt the data in the file A10076795.gz:

....
idea -e 'abcd2345 $+*LMNO' A10076795.gz
....

The encrypted data is put in the file A10076795.gz.id. Once this file is
transmitted, the receiver can then decrypt it, as long as he has the
key, with:

....
idea -d 'abcd2345 $+*LMNO' A10076795.gz.id
....

The decryped data is put in the file A10076795.gz.

Note that the quotes around the key are interpreted by the shell and
simply delimit the key string.

== SOURCE

*/appl/cmd/idea.b* +
*/utils/idea/idea.c*
