= mux: interactive television demo


*mux/mux*


_Mux_ is a standalone application environment run from the Inferno
console in _emu_(1) or started automatically by _init_(8) in a native
environment. It directly uses the _draw_(3) device and either keyboard
or Infrared, and cannot be run under _wm_(1). It is included in this
release only as an example of the use of the Prefab graphics module
described by _prefab-intro_(2). The simpler style of graphics and
interaction provided by Prefab and demonstrated by _mux_ might be more
appropriate than Tk on devices that use infrared remote control for
interaction, such as televisions, or devices with limited screen space,
such as pocket devices or portable telephones.

== Configuration

_Mux_ produces a menu derived from the configuration file
*/services/basic*. Each line in the file has three fields, separated by
*:*, of the following form:

________________________________
__icon__**:**__app__**:**_label_
________________________________

The _icon_ is the name of a bitmap file to displayed in the menu
alongside the textual _label_ (which is the rest of the line). When the
item is selected, as described below, _mux_ runs the Dis file

__________________________
**/dis/mux/**__app__*.dis*
__________________________

== Applications

The following applications are available:

*fnn*::
  Financial reports: a scrolling `ticker tape' along the bottom of the
  screen.
*movie*::
  Movies: select a film from a menu of categories
*news*::
  Today's Newspaper: on-screen newspapers
*tv*::
  Television
*tvlist*::
  TV Timetable
*pizza*::
  Order Pizza
*email*::
  Internet mail
*web*::
  Internet Web Browser: simplistic web browser
*register*::
  Register with a service provider
*ovid*::
  Presentations
*audioctl*::
  Audio Control

== Interaction

_Mux_ can be controlled using an infrared device, but for demonstration
purposes under _emu_(1) the infrared is emulated using the keyboard (see
_ir_(2)). The following are the common controls:

*r*::
  channel up
*c*::
  channel down
*t*::
  volume up
*v*::
  volume down
*i*::
  cursor up
*m*::
  cursor down
*j*::
  cursor left; rewind
*k*::
  cursor right; fast forward
*x*::
  return to main menu leaving application running; recall
*newline*::
  select item
*space*::
  exit and return to the previous screen or menu

== FILES

*/services/basic* +
*/icons/*.bit*

== SOURCE

*/appl/mux*

== SEE ALSO

_wm_(1), _ir_(2), _prefab-intro_(2), _virgil_(2), _manufacture_(8),
_register_(8), _signer_(8), _virgild_(8)

== BUGS

The video demonstrations currently work only on native machines with
specific hardware. +
For copyright reasons, some databases are not distributed, or have
randomly-generated content.
