std, if, while, ~, no, !, apply, getlines, status, pctl, fn, and, or,
raise, rescue, hd, tl, index, split, join, pid, parse, pipe, env -
standard shell builtins module.


*load std*

*!* _command_ +
*~* _value_ [ _pattern_... ] +
*no* [ _arg_... ] +
*and* _command_... +
*apply* _command_ [ _arg_... ] +
*getlines* [ _separators_ ] _command_ +
*flag* _f_ [ *+-* ] +
*for* _var_ *in* [ _arg_... ] _command_ +
*fn* _name command_ +
*if* _condition action_ [ _condition action_ ]... [ _elseaction_ ] +
*or* _command_... +
*pctl* _flag..._ +
*raise* _name_ +
*rescue* _pattern rescueblock command_ +
*status* _value_ +
*subfn* _name command_ +
*while* _condition command_ +
*$\{hd* __list__**}** +
*$\{index* _number_ __list__**}** +
*$\{pid}* +
*$\{split* [ _separators_ ] __arg__**}** +
*$\{join* _separator_ __list__**}** +
*$\{tl* __list__**}** +
*$\{parse* __arg__**]** +
*$\{pipe* ( *from* | *to* | _fdnum_ ) __command__**}** +
*$\{env}*


*Std* is a loadable module for _sh_(1) that provides the equivalent of a
``standard library'' for the shell, including a set of control-flow
constructs and some other miscellaneous commands. In the following
descriptions, if an argument is executed, then it should be a braced
block suitable for executing by _sh_. A true exit status is defined to
be nil; any non-nil exit status is false. Unless otherwise stated, the
return value of a command is that of the last command that it executed.
If invalid arguments are passed to any command, a *usage* exception is
raised, and a message printed to stderr.

Each of the looping commands *for*, *apply*, *while*, and *getlines*
installs an exception handler for the duration of the loop to catch the
exceptions *break* and *continue*. If a *break* exception is caught, the
loop is terminated; if a *continue* exception is caught, the loop will
continue executing as usual. The commands are as follows:

*!*::
  *!* inverts the exit status of a command (non-null is changed to null,
  null is changed to non-null).
*~*::
  *~* matches _value_ against each _pattern_ in turn, returning true if
  any of them match and false otherwise. The patterns are of the same
  form as those accepted by the shell for filename pattern matching
  except that / is not treated specially. (see _filepat_(2)). Patterns
  must be quoted to stop the shell from interpreting them.
*no*::
  True if there are no arguments. Useful for testing if there are any
  items in a list without counting the items with *$#*.
*and*::
  *And* evaluates each _command_ in turn until one returns false.
*apply*::
  *Apply* evaluates _command_ once for each _arg_, passing it in the
  variable *$1*.
*getlines*::
  *Getlines* reads lines from the standard input, executing _command_
  for each line, setting the environment variable *$line* to the line
  read, with any terminating character removed. If _separators_ is
  given, a line is terminated when any character in _separators_ is
  found; the default separator string is a single newline character.
*flag*::
  Either set (*+*), clear (*-*), or test (neither *+* or *-*) the flag
  _f_, where _f_ is a single character, one of the command line flags to
  _sh_ (see _sh_(1)).
*fn*::
  *Fn* defines a new builtin command named _name_; when run, this
  command evaluates _command_. The command is stored in the environment
  variable **fn-**__name;__ any variables of this form found when when
  *std* is loaded will be defined in this way. If _command_ is not
  given, then the builtin will be removed.
*subfn*::
  *Subfn* is similar to *fn* except that it defines a new substitution
  builtin _name_. When _name_ is invoked, it creates a new local
  variable *result* and executes _command_. The value of *$result* when
  _command_ has terminated is the value yielded by the substitution
  builtin _name_. _Command_ is stored in and restored from the
  environment in a similar way to *fn*, except that **sfn-**__name__ is
  used as the name of the environment variable.
*if*::
  *If* executes _condition_; if it returns true, then _action_ is
  executed, otherwise each of the next _condition_-_action_ pairs is
  evaluated in the same way; if no _condition_ is satisfied, then
  _elseaction_ will be executed, if present.
*for*::
  *For* is similar to *apply*; it runs _command_ once for each _arg_,
  but it performs a local assignment of _arg_ to _var_ each time.
*or*::
  *Or* evaluates each _command_ in turn until one returns true.
*pctl*::
  *Pctl* is an interface to the Inferno system call _sys-pctl_(2); each
  argument specifies one bit in the bitmask passed to that function. The
  possible flags are *newfd*, *forkfd*, *newns*, *forkns*, *newpgrp* and
  *nodevs*. See _sys-pctl_(2) for details of the meaning of these flags.
  *Pctl* returns true.
*raise*::
  *Raise* raises the exception _name_; _name_ will be truncated if it is
  longer than that allowed by _raise_ (128 bytes in _utf_(6)
  representation). Control will be transferred to the innermost rescue
  block in the same process that matches _name_. If there is no rescue
  block in place, the current process will exit, yielding _name_ as its
  exit status. If no _name_ is given, the exception named in
  *$exception* is raised; if this is null, a *bad raise context*
  exception is raised. The default command prompt catches all
  exceptions.
*rescue*::
  *Rescue* executes _command_ with an exception handler installed for
  the duration of the call. It will catch all exceptions with a name
  matching _pattern_, where _pattern_ is of the same form accepted by
  Limbo's *exception* handling statement. Specifically, the pattern is a
  string that matches literally, except that a trailing `*****'
  character will match any sequence of characters. If an exception is
  caught, *rescue* executes _rescueblock_, setting *$exception* to the
  name of the exception raised.
*status*::
  returns its first argument word as its exit status, or nil if none is
  given.
*while*::
  *While* repeatedly executes _condition_ and then _action_ until
  _condition_ does not return true.
*$\{env}*::
  *Env* yields a list of the names of all currently set non-nil
  environment variables.
*$\{hd}*::
  *Hd* yields the first of its arguments, or nil if there are no
  arguments.
*$\{index}*::
  *Index* yields the _n_'th element in its argument list, indexed from
  1. _N_ must be a decimal integer.
*$\{join}*::
  *Join* yields a single element which is the concatenation of all the
  elements in _list_ separated by _separator_. If there are no elements
  in _list_, it yields an empty string. The shell operator $"var is
  exactly equivalent to **$\{join ' ' $**__var__*}.*
*$\{parse}*::
  *Parse* parses _arg_ according to the usual syntax rules, raising a
  *parse error* exception if it fails. _Arg_ must be a well-formed
  command block surrounded by braces. *Parse* yields a functionally
  equivalent version of _arg_.
*$\{pid}*::
  *Pid* yields the process id of the current process.
*$\{pipe}*::
  *Pipe* runs _command_ asynchronously, with one of its file descriptors
  connected to a bidirectional pipe. The first argument to *pipe*
  determines which file descriptor is connected: if the argument is
  *from*, its standard output is connected; if the argument is *to*, its
  standard input is connected; otherwise file descriptor _fdnum_ is
  connected. *Pipe* yields the name of a file that can be opened to
  access the other end of the pipe. Note that this command is now
  deprecated in favour of the *<\{}* redirection operator built in to
  the shell.
*$\{split}*::
  *Split* splits _arg_ into list elements at every point where one or
  more characters in _separators_ appear. If _separators_ is not given,
  the value of *$ifs* is used.
*$\{tl}*::
  *Tl* yields all but the first of its arguments, or nil if there are no
  arguments.

== Syntactic considerations

It is worth being aware of a few pitfalls that await the user of some of
these commands. Unlike other shells, the syntax of _sh_ does not include
the syntax of the control flow commands, so it is important to be aware
of the rules that govern the gathering of the arguments for a command.
In particular, the following code, written to print a message a filename
ends in *.b* will not work: it will always print ``file is Limbo
source''.

....
	and
		{~ $filename '*.b'}
		{echo file is Limbo source}
....

This is because newlines separate shell commands, so the above code
first invokes *and* with no arguments, and then each of the braced block
commands on each subsequent line. It is usual to use round brackets in
order to group together arguments on separate lines, e.g.

....
	and (
		{~ $filename '*.b'}
		{echo file is Limbo source}
	)
....

This has the originally intended meaning.

== FILES

*/tmp/pipe.*d*::
  Temporary placeholder directory for named pipes.
*/tmp/pipes/**::
  Mount point for named pipes.

== SOURCE

*/appl/cmd/sh/std.b*

== SEE ALSO

_sh_(1), _sh-expr_(1), _sh-tk_(1)
