NPROC = 1
FILES = \
	title.ps \
	bltj.ps \
	styx.ps \
	asm.ps \
	changes.ps \
	gridinstall.ps \
	ebookimp.ps \
	styx.ps \
	mk.ps \
	asm.ps \
	compiler.ps \
	sh.ps \
	dis.ps \
	acid.ps \
	acidpaper.ps \
	acidtut.ps \
	mk.ps \
	asm.ps \
	compiler.ps \
	port.ps \
	hotchips.ps \
	install.ps \

DIRS = \
	limbo \
	perform \
#	limbotk \

all:V: dirs

print:V: \
	title.ps \

dirs:V:	$FILES $DIRS mkfile
	for(i in $DIRS) @{
		cd $i
		mk
	}

%.ps:D:	%.ms
	cat $stem.ms | tbl | troff -mpm | lp -dstdout > $target

gridinstall.ps:D:	gridinstall.ms
	cat gridinstall.ms | tbl | troff -ms | lp -dstdout > $target

title.ps:D:	title
	troff $prereq | lp -dstdout > $target

changes.ps:D:	changes.ms
	tbl changes.ms | troff -ms | dpost >$target

%.pdf: %.ps
	ps2pdf <$stem.ps >$stem.pdf
