<../../mkconfig

TARG=6a

OFILES=\
	y.tab.$O\
	lex.$O\

HFILES=\
	../6c/6.out.h\
	y.tab.h\
	a.h\

YFILES=a.y\

LIBS=cc bio 9		# order is important


<$ROOT/mkfiles/mkone-$SHELLTYPE

YFLAGS=-D1 -d
CFLAGS=	$CFLAGS -I../include

lex.$O:	../cc/macbody ../cc/lexbody

$LIBDIR/libcc.a:
	cd ../cc
	mk $MKFLAGS install
	mk $MKFLAGS clean
