<$ROOT/mkconfig

DIRS=\
	acme\
#	alphabet\
	charon\
	cmd\
	collab\
	demo\
	ebook\
	grid\
	lib\
	math\
#	mux\
	spree\
	svc\
	tiny\
	wm\

<$ROOT/mkfiles/mksubdirs


BINTARG=${TARG:%=$DISBIN/%}
MODDIR=$ROOT/module
SYS_MODULE=${SYSMODULES:%=$ROOT/module/%}
LIMBOFLAGS=-I$ROOT/module

all:V:		$TARG

install:V:	$BINTARG

installall:V:	install

clean:V: 	clean-std

nuke:V:		nuke-std

$DISBIN/%.dis:	%.dis
	rm -f $DISBIN/$stem.dis && cp $stem.dis $DISBIN/$stem.dis

%.dis:		$MODULES $SYS_MODULE

%.dis:		%.b
	limbo $LIMBOFLAGS -gw $stem.b

%.s:		%.b
	limbo $LIMBOFLAGS -w -G -S $stem.b

%.install:V:	$DISBIN/%.dis
%.installall:V:	$DISBIN/%.dis

clean-std:V:
	rm -f *.dis *.sbl

nuke-std:V:	clean-std
	cd $DISBIN; rm -f $TARG
