
<../../../mkconfig

TARG=\
	print.dis \
	hp_driver.dis \
	scaler.dis \


MODULES=\
	scaler.m \


SYSMODULES= \
	bufio.m\
	draw.m\
	string.m\
	sys.m\
	print.m \


DISBIN=$ROOT/dis/lib/print

<$ROOT/appl/mkfile
# force compilation or it's very slow
LIMBOFLAGS= -c $LIMBOFLAGS
