= audio: Inferno audio file format


Inferno audio files accepted by commands such as _auplay_(1) have a
simple format. The file contains a header consisting of non-empty lines
of text specifying the data format and characteristics, followed by an
empty line, followed by the audio data in binary form. The data can be
copied directly to a suitable audio device (see _audio_(3)) correctly
configured, using *read*, *write* or *stream* (see _sys-read_(2)).

Each header line corresponds to a command that can be written to the
control file *audioctl* of the _audio_(3) device. The first line of the
header must be a *rate* command; other commands can appear in any order.
The commands available are:

**rate**__ n__::
  The data was recorded at _n_ Hz, typically one of *44100*, *22050*,
  *11025* or *8000* but other values are legal.
**chans**__ n__::
  There are _n_ channels of audio data (eg, 1 for mono and 2 for
  stereo).
**bits**__ n__::
  Each sample is _n_ bits (typically 8 or 16).
**enc**__ e__::
   +
  The string _e_ gives the recording format, and will usually be one of
  the following: *ulaw*, *alaw*, *pcm* or *adpcm*.

The audio data is stored with a sample from each channel in turn (`left'
sample first if stereo, regardless of encoding or data size). Data
encoded as *pcm* is little-endian, 2's complement if 16-bit, but
unsigned if 8 bit. The *adpcm* encoding uses 4-bit samples (two mono
samples or one stereo sample per byte, again little-endian).

== SEE ALSO

_auplay_(1), _audio_(3)
