= namespace: name space description file


Namespace files describe how to construct a name space from scratch, or
add to an existing name space. The files are interpreted by _newns_(2),
invoked by commands such as _logon_(1) and by other system services.

The name space description file contains one or more lines each of which
specifies one name space operation. Empty lines and lines with *#* as
the first non-space character are ignored. Environment variables of the
form **$**__name__ are expanded within arguments, where _name_ is a
string terminated by white space, or one of the characters

or

The known operations and their arguments are:

*bind [-abci] old new*::
  Use _new_ as an alias for file or directory _old_. Options *a*, *b*
  and *c* translate to flag values *Sys->MAFTER*, *Sys->MBEFORE* and
  *Sys->MCREATE* of _sys-bind_(2). If neither *a* nor *b* are given, the
  default is *Sys->MREPL*. Option *i* means to ignore errors.
*cd directory*::
  Change working directory to _directory_.
*fork*::
  Split the name space before modification. This is equivalent to
  passing a value of *Sys->FORKNS* to _sys-pctl_(2).
*mount [-abc9i] [-k keyfile] [-C alg] [net!]machine[!svc] dir [spec]*::
  Mount the file tree of _machine_ upon directory _dir_. The default
  service is *styx*. Options *a*, *b*, *c* and *i* are the same as for
  *bind*. The tokens _dir_ and _spec_ translate to _old_ and _aname_ of
  *mount* as described under _sys-bind_(2). The *-k*, *-C* and *-9*
  options are the same as those for the _mount_ command (see _bind_(1)).
*import [-abc9i] [net!]machine[!svc] [remotedir] dir*::
  Import a directory from a remote Plan 9 _machine_ and make it appear
  on directory _dir_. Options *a*, *b*, *c* and *i* are the same as for
  *mount*. By default, _remotedir_ is assumed to be the same name as
  _dir_. The default service is *exportfs*. (Currently this operation
  works only under native Inferno and Plan 9.)
*new*::
  Create a new name space in which the current directory becomes the
  root directory; typically used after *cd*. This is equivalent to
  passing a value of *Sys->NEWNS* to _sys-pctl_(2).
*nodev*::
  Disallow device attaches. This is equivalent to passing a value of
  *Sys->NODEVS* to _sys-pctl_(2).
*unmount [-i] [name] from*::
  If two arguments are given, undo a *bind* or *mount* with the same
  arguments. If only one argument is given, everything bound to or
  mounted on _from_ is unmounted. The *-i* option means ignore errors.
**.**__ path__::
  Include the name space description file _path_.

== SEE ALSO

_nsbuild_(1), _wm_(1), _newns_(2)
