= plumbing: plumbing rules


Plumbing rules tell _plumber_(8) how to route plumbing messages
generated by applications using _plumbmsg_(2).

The file is a set of rules separated by blank lines. Each rule is a set
of patterns followed by a set of actions. The rules are interpreted in
order. The first rule whose patterns all match is applied, and no
further rules are examined. Comments start with *#* and continue to end
of line. Single quotes protect special characters (use *''* to get a
single quote).

A pattern has the general form:

________________
_field verb arg_
________________

Each _field_ corresponds to a field in the incoming plumbing message:

____________________________________________
*src*::
  Source application
*dst*::
  Destination port
*dir*::
  Working directory
*kind*::
  Format of the data (eg, *text* or *image*)
*attr*::
  A line of __name__**=**_value_ pairs
*data*::
  The message data (an array of bytes)
____________________________________________

The verbs are:

_____________________________________________________________________________________________________________________
*is*::
  Exact string comparison with _arg_
*matches*::
  Regular expression comparison with _arg_
*isdir*::
  _Arg_ must name an existing directory
*isfile*::
  _Arg_ must name an existing file
*set*::
  Set the value of the _field_ to _arg_. This verb operates in place, so
  put it after all other patterns in the rule.
_____________________________________________________________________________________________________________________

The _arg_ can refer to one of the following variables:

________________________________________________________________________________________________________________________________________________
*$0* to *$9*::
  Substrings resulting from the most recent regular expression match:
  *$0* is the entire substring; *$1* the first parenthesised substring,
  etc.
*$file*::
  The file name examined by the last *isfile* verb.
*$dir*::
  The directory name examined by the last *isdir* verb.
________________________________________________________________________________________________________________________________________________

The following actions are provided:

_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
**plumb to**__ port__::
  Route the message to the given plumbing _port_.
**plumb start**__ command arg ...__::
  If no program is currently listening on the current rule's _port_,
  start the _command_ with the given arguments. The `**$**' variables
  listed above can be used, to include part of the message in the
  command line arguments to the program. They are replaced in the
  command string by their actual values.
_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

For example, the following rule sends the names of module files- file
names ending with suffix `**.m**'- to _wm-brutus_(1), starting it if it
is not already running:

....
kind is text
data matches '([a-zA-Z0-9]+`m)(:[0-9]+)?'
data isfile     /module/$1
data set        /module/$0
plumb to edit
plumb start /dis/wm/brutus.dis $file$2
....

Note the use of *$2* in the *start* action to pass *brutus* the line
number selected by the second parenthesised expression in the pattern.

== FILES

**/usr/**__user__*/lib/plumbing*

== SEE ALSO

_plumb_(1), _plumbmsg_(2), _plumber_(8)
