= proto: file system prototype


A _proto_ file defines a file system hierarchy, for programs that
create, copy or operate on them, such as _fs_(1) or _mkfs_(8). The
_proto_ file defines the hierarchy as a set of names relative to an
existing hierarchy, for instance in an existing file system or a list of
path names in an archive. Files in the existing hierarchy that are not
specified in the _proto_ file are ignored. _Fsproto_(2) provides
functions to read a prototype file and enumerate the names it selects in
an existing hierarchy.

Each line of the _proto_ file specifies a file (where the term `file'
includes directories). Indentation is significant, with each level of
indentation corresponding to a level in the file tree. Each line
contains up to five fields separated by white space:

....
name perm uid gid source
....

_Name_ is the last path element in the resulting file tree. _Perm_
specifies the permissions, as described below. _Uid_ is the owner of the
file, and _gid_ is the group owning the file. _Source_ is the name of a
file in the current name space (not the source file tree) from which to
copy _name_'s content. All fields except _name_ are optional. If a field
such as _perm_ or _uid_ is not given, or is given as

its value is taken from the existing file.

A _name_ starting with

is taken as a reference to an environment variable (see _sh_(1) and
_env_(3)) and replaced by the value of that variable. If the first
_name_ in a directory is

all of the files are represented, and all subdirectories recursively. If
the first _name_ is

all of the names in the corresponding existing directory are
represented, but only the names of subdirectories, not their content. If
the first _name_ is

only non-directory names are represented excluding both the names and
content of subdirectories.

_Perm_ has the form:

_______________________
[*d*] [*a*] [*l*] _oct_
_______________________

where the optional letters set file attributes

directory,

append-only, and

exclusive-use), and _oct_ is an octal number giving the permissions for
user, group and others (see _chmod_(1)).

== EXAMPLES

Denote all files in a given file system:

....
+
....

Denote all files in the current user's home directory:

....
usr
	$user
....

Specify a subset of files in */dis*:

....
dis
	*
	install
		*
	lib
		arg.dis
		names.dis
....

== FILES

*/lib/proto*::
  directory of prototype files
*/lib/proto/all*::
  prototype for whole hierarchy (ie, line containing

*/lib/proto/portproto*::
  generic prototype file

== SEE ALSO

_fs_(1), _fsproto_(2), _kfs_(4), _mkfs_(8)
