= regexp, regex: regular expression notation


A _regular expression_ specifies a set of strings of characters. A
member of this set of strings is said to be _matched_ by the regular
expression. In many applications a delimiter character, commonly

bounds a regular expression. In the following specification for regular
expressions the word `character' means any character (rune) but newline.

The syntax for a regular expression *e0* is

....
e3:  literal | charclass | '.' | '^' | '$' | '(' e0 ')'

e2:  e3
  |  e2 REP

REP: '*' | '+' | '?'

e1:  e2
  |  e1 e2

e0:  e1
  |  e0 '|' e1
....

A *literal* is any non-metacharacter, or a metacharacter (one of
*.*+?[]()|\^$*), or the delimiter preceded by

A *charclass* is a nonempty string _s_ bracketed **[**__ s __*]* (or
**[^**__s __*]);* it matches any character in (or not in) _s_. A negated
character class never matches newline. A substring __a__**-**_b,_ with
_a_ and _b_ in ascending order, stands for the inclusive range of
characters between _a_ and _b_. In _s_, the metacharacters

an initial

and the regular expression delimiter must be preceded by a

other metacharacters have no special meaning and may appear unescaped.

A

matches any character.

A

matches the beginning of a line;

matches the end of the line.

The *REP* operators match zero or more (***), one or more (*+*), zero or
one (*?*), instances respectively of the preceding regular expression
*e2*.

A concatenated regular expression, *e1 e2*, matches a match to *e1*
followed by a match to *e2*.

An alternative regular expression, *e0 | e1*, matches either a match to
*e0* or a match to *e1*.

A match to any part of a regular expression extends as far as possible
without preventing a match to the remainder of the regular expression.

== SEE ALSO

_acme_(1), _sh-regex_(1), _regex_(2)
