objtype=power
OBJTYPE=$objtype
<$ROOT/mkconfig

LIB=libmp.a
SFILES=\
	mpvecadd.s\
	mpvecdigmuladd.s\
	mpvecdigmulsub.s\
	mpvecsub.s\

HFILES=$ROOT/arch/$SYSTARG/$OBJTYPE/include/u.h $ROOT/include/mp.h ../port/dat.h

OFILES=${SFILES:%.s=%.$O}

UPDATE=mkfile\
	$HFILES\
	$SFILES\

<$ROOT/mkfiles/mksyslib-$SHELLTYPE
