<$ROOT/mkconfig

all:V:          all-$HOSTMODEL
install:V:      install-$HOSTMODEL
safeinstall:V:  safeinstall-$HOSTMODEL
clean:V:        clean-$HOSTMODEL
nuke:V:         nuke-$HOSTMODEL

&-Posix:QV:
	echo "(cd $SYSTARG/emu; mk $MKFLAGS $stem)"
	(cd $SYSTARG/emu; mk $MKFLAGS $stem) || exit 1

&-Nt:QV:
	echo '@{builtin cd' $SYSTARG '/emu; mk $MKFLAGS $stem}'
	@{builtin cd $SYSTARG/emu; mk $MKFLAGS $stem }

&-Plan9:QV:
	echo '@{builtin cd' $SYSTARG '/emu; mk $MKFLAGS $stem}'
	@{builtin cd $SYSTARG/emu; mk $MKFLAGS $stem }
