= ftree: file tree browser


*wm/ftree* [ *[-e* ] [ *-E* ] [ *-p* ] [ *-d* ] [ _root_ ]


_Ftree_ displays the given _root_ directory (default: */*) in a
graphical form as a tree. Files and subdirectories are listed beneath
the directory that contains them. Initially, the contents of a
subdirectory are not displayed, but selecting the *⊕* symbol next to its
name with button 1 causes its contents to be displayed there, and the
*⊕* symbol changes to *⊖*; clicking that collapses the subdirectory
display back to its name. (If the directory is empty, the circle will be
empty.) Selecting a file or directory name with button 1 pops up a menu
of operations: *Open*, *Copy*, *Paste into*, and *Remove*. *Open* plumbs
the full path name of the file or directory; it is up to the
_plumber_(8) to act appropriately based on the structure of the file
name, as controlled by the user's _plumbing_(6) file. Typically images
will be displayed in a separate window, source files will be opened in
an editor, and so on. Directory structure can be copied by invoking
*Copy* on the source, then *Paste into* on the destination directory.
The *-d* option disallows all operations except *Open*.

Normally, _ftree_ displays the usual _wm_(1) controls, and interprets
them as usual. The other options change that behaviour:

*-e*::
  Ignore `exit' but offer move or resize.
*-E*::
  Ignore exit, and do not offer move or resize.
*-p*::
  Do exit, but do not offer move or resize.

The different options are used to program a user interface for handheld
touch screen devices. For instance, a start panel can be created by
invoking _ftree_ with the *-E* option, ensuring that the _ftree_ screen
is always there, and all subsequent interaction can be controlled by the
construction of the _root_ namespace and suitable choice of plumbing
rules.

== SOURCE

*/appl/wm/ftree*

== SEE ALSO

_filename_(1), _wm_(1), _plumbing_(6), _plumber_(8)
