= expr, ntest, mpexpr: shell module for simple arithmetic.


*load expr* OR *load mpexpr*

*$\{expr* [ -r _radix_ ] [ _arg..._ ] *}* +
*ntest* _num_ +


_Expr_ and _mpexpr_ are loadable modules for _sh_(1) that provide
support for integer arithmetic. _Expr_ uses 64-bit signed integers;
_mpexpr_ uses arbitrary-precision signed integers. They each provide the
same interface: a command _ntest_, which performs a simple boolean test
on its integer argument, and the substitution operator _expr_, which
takes an expression in Reverse Polish notation, and yields its result.

_Ntest_ returns true if its argument _num_ is non-zero, and false
otherwise.

_Expr_ evaluates each _arg_ in turn; if it is an integer it gets pushed
onto the stack; otherwise it should name one of the operators below,
whereupon the appropriate number of operands are popped off the stack,
evaluated as arguments to the operator, and the result pushed back onto
the stack. Arguments are passed to the operator first-pushed first, so,
for instance, *$\{expr 2 1 -}* yields 1, not -1. Alternative names are
given for some operators; this is to avoid the necessity of quoting
operators that contain _sh_(1) metacharacters. Integers are given in the
same form acceptable to Limbo. The relational operators yield either 1
(true) or 0 (false). If the *-r* option is given, _radix_ specifies an
output base for printed numbers. It may be from 2 to 36; _mpexpr_ also
allows 64 to specify base64 notation. Numbers are printed in a form
suitable for re-interpretation by _expr_.

When all its arguments have been evaluated, *expr* yields all the values
remaining on its stack, first pushed first. Note that bitwise operators
treat their operands as if they were stored in two's complement form.
The operators supported by expr are as follows (the number of operands
required in is given parentheses).

*+* (2)::
  Addition
*-* (2)::
  Subtraction
*x*, *** (2)::
  Multiplication
*/* (2)::
  Division. Division by zero raises a *divide by zero* exception.
*%* (2)::
  Modulus. A zero modulus will cause a *divide by zero* exception to be
  raised.
*and* (2)::
  Bitwise-and.
*or* (2)::
  Bitwise-or.
*xor* (2)::
  Bitwise-xor.
*~* (1)::
  Bitwise-complement..
*_* (1)::
  Unary minus.
*<<*, *shl* (2)::
  Shift left.
*>>*, *shr* (2)::
  Shift right.
*=*, *==*, *eq* (2)::
  Equality.
*!=*, *neq* (2)::
  Inequality.
*>*, *gt* (2)::
  Greater than.
*<*, *lt* (2)::
  Less than.
*<=*, *le* (2)::
  Less than or equal to.
*>=*, *ge* (2)::
  Greater than or equal to.
*!*, *not* (1)::
  Logical negation.
**rep**__ (n)__::
  *Rep* repeats the last operation (which must have been a two-operand
  operation other than *seq*) until the values in the stack are
  exhausted.
*seq* (2)::
  *Seq* pushes on the stack a sequence of numbers ranging numerically
  from its first argument up to and including its second argument. If
  its second argument is less than its first, the sequence will descend.
*rand* (1)::
  (_mpexpr_ only). Push a secure random number; the argument value gives
  the size of the number, in bits.
*bits* (1)::
  (_mpexpr_ only). Push the size, in bits, of the argument.
*expmod*, *invert* (2)::
  (_mpexpr_ only). See _keyring-ipint_(2).
*exp*, *xx*, ****::
  (_mpexpr_ only). Exponentiation.

== SOURCE

*/appl/cmd/sh/expr.b*

== SEE ALSO

_sh_(1), _sh-std_(1), _sh-tk_(1), _keyring-ipint_(2)

== BUGS

Postfix notation can be confusing. Any operators that contain shell
metacharacters (e.g. ``*'', ``>'') must be quoted to avoid
interpretation by the shell. Base64 notation can contain # characters,
which need quoting to avoid interpretation by the shell.
