= init: emuinit, osinit: Inferno initialisation

== SYNOPSIS

....
Init: module
{
	init: fn();
};
....

*/dis/emuinit.dis*

*#/./osinit.dis*


Both _emu_(1) and the native kernels run a Dis program to initialise the
system.

_Emuinit_ is the default initialisation program for _emu_(1). _Emu_ sets
the environment variable (see _env_(3)) */env/emuargs* to the command
line originally given to _emu_, which has the following form:

_______________________________________
*emu* [*-d*] [ _command_ [_ arg ..._] ]
_______________________________________

_Emuinit_ uses the value of *emuargs* to decide which command to start
and its arguments. The default _command_ is */dis/sh.dis*, unless the
*-d* option is given, in which case */dis/lib/srv.dis* is used by
default instead, to cause _emu_ to run on the host system as a server
(`daemon' mode).

_Osinit_ is built-in to the _root_(3) of native kernels. Although the
kernel uses the fixed name *#/./osinit.dis* the contents are taken from
one of the files in */os/init* selected by the *init* section of the
kernel configuration file. _Osinit_'s action is platform-specific in
detail, but might include: building an initial */dev* by mounting device
drivers; binding the physical network driver (eg, _ether_(3)) into
*/net* and initialising _ip_(3), usually setting addresses and routes
using *bootp*; attaching to a remote file system; setting up flash
translation using _ftl_(3); starting _dossrv_ or _9660srv_ (see
_dossrv_(4)), or _kfs_(3) to serve local files from disk or flash
memory.

== FILES

*/env/emuargs*

== SOURCE

*/appl/cmd/emuinit.b* +
*/os/init/*.b*

== SEE ALSO

_emu_(1)
