= rstyxd: Styx-based remote execution and file service

== SYNOPSIS

*auxi/rstyxd* _alg_ ...


_Rstyxd_ provides a remote-execution service. Having authorised the
client and optionally established _ssl_, as described above, it reads a
single line from its standard input. The line contains a decimal value
that is the count of the number of bytes that follow, which _rstyxd_
reads as a _utf_(6)-encoded string. The string contains a command, which
is parsed into arguments, following the quoting conventions of _sh_(1).
The first argument is the command name. _Rstyxd_ prepares a modified
name space in which to run the command. It mounts the connection
(standard input) on */n/client*, binds */n/client/dev* onto */dev*, and
opens the new */dev/cons* (ie, the remote client's */dev/cons*) on file
descriptors 0, 1 and 2. Finally, it executes the command.

_Rstyxd_ is normally started by _svc_(8) in response to incoming network
calls. It expects the standard input to be connected to the client;
unusually, it is both read and written. It first authenticates the
incoming call using _keyring-auth_(2) via _security-auth_(2). On
successful authorisation, the server sets its user identity to that of
the caller, and the client can request that a digest and/or encryption
algorithm be applied using _ssl_(3) to protect the data exchanged with
the server. Each _alg_ names a digest or encryption algorithm that the
server will allow the client to use, in any form accepted by _ssl_; the
special name *none* is usually listed, to allow the client to choose not
to use _ssl_.

== FILES

*/n/client*::
  mount point used by _rstyxd_
**/usr/**__user__*/keyring/default*::
  server's authentication data when _svc_(8) run as given _user_

== SOURCE

*/appl/cmd/auxi/rstyxd.b*

== SEE ALSO

_keyring-auth_(2), _security-auth_(2), _getauthinfo_(8)
