= fs: file-hierarchy traversal

....
load alphabet
typeset /fs
type /fs/fs
type /fs/entries
type /fs/gate
type /fs/selector
....

*Fs* is a typeset for _alphabet_ (see _sh-alphabet_(1)) which enables
filtering of the contents of hierarchical filesystems. _Fs_ defines four
new types:

*fs*::
  The complete contents of a filesystem.
*entries*::
  Information about the entries in a filesystem without their content.
*gate*::
  A condition that can be used with conditional verbs. A gate is open to
  entries satisfying particular criteria.
*selector*::
  A comparator which compares two entries and selects one, both or
  neither of them.

In the following description of the verbs provided, an entry such as:

*print _entries_ -> status*::

describes a verb *print*, which takes one argument of type _entries_,
and the result of which is of type *status*. If the type is not one of
those described above, it should be taken to be of type _string_.

All types and modules names are taken to be relative to the typeset
root, */fs*.

Modules defined within _fs_ include:

and _gate gate_ [_gate_...] -> _gate_::
  *And* is a gate that is open to an entry if all its arguments are
  open.
bundle _fs_ -> _void_::
  *Bundle* converts _fs_ to an archival format and writes it to the
  standard output.
compose [-d] _op_ -> _selector_::
  *Compose* implements ``compositing''-style operators, useful when
  merging filesystems. _Op_ specifies the operator, taking its name from
  the graphical Porter-Duff equivalent: *AinB*, *AinB*, *BinA*, *AoutB*,
  *BoutA*, *A*, *AoverB*, *AatopB*, *AxorB*, *B*, *BoverA*, or *BatopA.*
  For instance, *AinB* gives the intersection of A and B; *AatopB* gives
  A whereever both A and B exist, and B otherwise. When used as a
  selector for *merge*, operators that exclude the union of A and B are
  not very useful, as they will exclude all common directories at the
  top level. Given the *-d* option, compose will allow through
  directories that would otherwise be excluded in this way, making
  operators such as *AxorB* (all that A does not hold in common with B)
  more useful, although accurate only for regular files.
depth _n_ -> _gate_::
  *Depth* is a gate open only to entries which are within _n_ levels of
  the root of the filesystem.
entries _fs_ -> _entries_::
  *Entries* produces all the entries contained within _fs_.
filter [-d] _fsgate_ -> _fs_::
  The result of *filter* is a filesystem from which all entries that
  will not pass through _gate_, and their descendents, have been
  removed. If the *-d* flag is given, only files are filtered -
  directories bypass the gate.
ls [-um] _entries_ -> _void_::
  Print each entry in the style of *ls -l* (see _ls_(1)). If the *-u*
  flag is given, the file access time rather than the file modification
  time will be printed. If the *-m* flag is given, the name of the user
  that last modified the file is printed too.
exec [-pP] [-t _cmd_] [-n _n_] _entries cmd_ -> _void_::
  Run its argument _cmd_ for each entry in _entries ._ If the *-n* flag
  is specified, *exec* will try to gather _n_ entries together before
  invoking the command (default 1). The environent variable *$file* is
  set to the names of the entries that have been gathered. If the *-p*
  flag is given, environment variables are set giving information about
  the mode, owner, modification time and size of the entry (they are
  named after the equivalent field names in the *Dir* structure; see
  _sys-stat_(2)). This option is only valid when _n_ is 1. The *-P* flag
  causes all the other fields in the Dir structure to be included too.
  Note that the command is run in the same shell context each time, so
  environment variable set on one execution can be retrieved on the
  next. The *-t* flag can be used to specify a command which will be
  executed just before termination.
match [-ar] _pattern_ -> _gate_::
  *Match* is a gate that is open if the entry's filename matches the
  _pattern_. If the *-a* flag is given, the whole path will be used for
  the match. If *-r* is specified, the pattern is evaluated as a regular
  expression, otherwise it is a shell-style pattern in the style of
  _filepat_(2).
merge [-1] [-c _selector_] _fs fs_ [_fs_...] -> _fs_::
  Recursively merge the contents of its argument filesystems. _Selector_
  is consulted to see which entries are chosen for the result; if not
  given, entries are resolved in favour of the first filesystem
  (equivalent to *\{compose AoverB}*). If the *-1* flag is given,
  merging takes place only in the top-level directory.
mode _spec_ -> _gate_::
  *Mode* is a gate that lets through entries whose file permissions
  satisfy _spec_, which is a string in the style of _chmod_(1). If the
  _op_ field is *+*, the specified permissions must be present; if *-*,
  they must be absent, and if *=*, they must be exactly as given. The
  directory and auth modes are specified with the characters ``d'' and
  ``A'' respectively.
not _gate_ -> _gate_::
  *Not* is a gate open to an entry if its argument is not.
or _gate gate_ [_gate_...] -> _gate_::
  *Or* is a gate open to an entry if any argument is open.
path [-x] _path_... -> _gate_::
  *Path* is a gate open to an entry whose full pathname is an ancestor
  or a descendent of any _path._ If *-x* is specified, the gate is open
  to any path _except_ descendents of the paths given.
pipe [-1pP] _fs cmd_ -> _status_::
  *Pipe* is similar to exec, except that the contents of all files in
  _fs_ are piped through _cmd_. Unless the *-1* option is given, _cmd_
  is started once for each file, with *$file* set to its name, and other
  environment variables set according to the *-p* or *-P* options, as
  for *exec*. If the *-1* option is specified, _cmd_ is started once
  only - all file data is piped through that.
print _entries_ -> _fd_::
  Print the path name of each entry to _fd_.
proto [-r _root_] _protofile_ -> _fs_::
  Evaluate _protofile_ as a _mkfs_(8) _proto_ file. If _root_ is
  specified, it will be used as the root of the resulting _fs_.
query _cmd_ -> _gate_::
  *Query* is a gate that runs _cmd_ to determine whether it is open: an
  empty exit status from the command yields an open gate. The
  environment variable *$file* is set for the command to the path name
  of the entry that is being queried for.
run _cmd_ -> _string_::
  *Run* runs _cmd_ and substitutes the value of the environment variable
  *$s* after its invocation. *$s* must have exactly one element.
select _gate entries_ -> _entries_::
  Select only those entries within _entries_ that will pass through
  _gate_. Descendents of elided entries are not affected.
setroot [-c] _fs_ _path_ -> _fs_::
  *Setroot* sets the name of the root directory of _fs_. If the *-c*
  flag is given, the elements in the root directory will be made
  explicit in the hierarchy (i.e. the name of the top directory will not
  contain any */* characters).
size _entries_ -> _fd_::
  Print the sum of the size of all entries, in bytes to _fd_.
unbundle _fd_ -> _fs_::
  *Unbundle* reads an archive as produced by *bundle* from _fd_; its
  result is the contents of the filesystem that was originally bundled.
walk _path_ -> _fs_::
  *Walk* produces a filesystem that is the result of traversing all the
  files and directories underneath _path_.
write _fs dir_ -> _void_::
  Write the contents of _fs_ to the filesystem rooted at _dir ._ If
  _dir_ is empty, _fs_ will be written to the root directory originally
  associated with fs.

== EXAMPLES

The examples below assume the following _alphabet_ declarations:

....
	load alphabet
	typeset /fs
	type /string /fd /fs/fs /fs/entries /fs/gate
	import /fs/size /fs/walk /fs/select /fs/mode /fs/merge
	import /fs/compose /fs/exec /fs/bundle /fs/write /fs/unbundle
	import /fs/print /fs/depth /fs/filter /fs/query
	autoconvert string fs walk
	autoconvert fs entries /fs/entries
	autoconvert string gate /fs/match
	autoconvert entries fd /fs/print
	autoconvert fd /status {(/fd); /print $1 1}
....

Print the size of all files below the current directory:

....
	-{size .}
....

Show the names of all files in x that aren't in y:

....
	-{walk x | merge -c {compose -d AoutB} y | select {mode -d}}
....

Remove all files from /appl ending in *.dis*:

....
	-{walk /appl | select '*.dis' | exec "{rm $file}}
....

Recursively copy the current directory to */tmp/foo*.

....
	-{write . /tmp/foo}
....

Interactively remove all regular files from one level of the current
directory:

....
	-{walk . |
		filter {depth 1} |
		select {mode -d} |
		select {
			query "{echo -n $file:; ~ `{read} y yes}
		} |
		exec "{rm $file}
	}
....

Create a new archive containing those files from below the current
directory that were held in an old archive:

....
	-{merge -c {compose AinB} . {unbundle old.bundle} |
		bundle |
		/create new.bundle
	}
....

== SOURCE

*/appl/alphabet/fs.b*, */appl/alphabet/fstypes.b*
*/appl/alphabet/auxi/fsfilter.b* +
*/appl/cmd/fs/*.b* +

== SEE ALSO

_sh-alphabet_(1), _alphabet-main_(1), _alphabet-fs_(2), _sh_(1)
