= dd: convert and copy a file


*dd* [ _option value_ ] ...


_Dd _ copies the specified input file to the specified output with
possible conversions. The standard input and output are used by default.
The input and output block size may be specified to take advantage of
raw physical I/O. The options are

**-if **__f__::
  Open file _f_ for input.
**-of **__f__::
  Open file _f_ for output.
**-ibs **__n __::
  Set input block size to _n _ bytes (default 512).
**-obs **__n __::
  Set output block size (default 512).
**-bs **__n __::
  Set both input and output block size, superseding _ibs _ and _obs_. If
  no conversion is specified, preserve the input block size instead of
  packing short blocks into the output buffer. This is particularly
  efficient since no in-core copy need be done.
**-cbs **__n __::
  Set conversion buffer size.
**-skip **__n __::
  Skip _n_ input records before copying.
**-iseek **__n __::
  Seek _n_ records forward on input file before copying.
**-files **__n __::
  Catenate _n_ input files (useful only for magnetic tape or similar
  input device).
**-oseek **__n __::
  Seek _n _ records from beginning of output file before copying.
**-count **__n __::
  Copy only _n_ input records.

-conv ascii Convert

to

____________________________________________________________
*ebcdic*::
  Convert

to

*ibm*::
  Like *ebcdic* but with a slightly different character map.
*block*::
  Convert variable length

records to fixed length.

*unblock*::
  Convert fixed length

records to variable length.

*lcase*::
  Map alphabetics to lower case.
*ucase*::
  Map alphabetics to upper case.
*swab*::
  Swap every pair of bytes.
*noerror*::
  Do not stop processing on an error.
*sync*::
  Pad every input record to _ibs _ bytes.
____________________________________________________________

Where sizes are specified, a number of bytes is expected. A number may
end with

or

to specify multiplication by 1024 or 512 respectively; a pair of numbers
may be separated by

to indicate a product. Multiple conversions may be specified in the
style:

is used only if

or

conversion is specified. In the first two cases, _n_ characters are
copied into the conversion buffer, any specified character mapping is
done, trailing blanks are trimmed and new-line is added before sending
the line to the output. In the latter three cases, characters are read
into the conversion buffer and blanks are added to make up an output
record of size _n_. If

is unspecified or zero, the

and

options convert the character set without changing the block structure
of the input file; the

and

options become a simple file copy.

== SOURCE

*/appl/cmd/dd.b*

== DIAGNOSTICS

_Dd_ reports the number of full + partial input and output blocks
handled.

== SEE ALSO

_cat_(1), _cp_(1)
