= itest, itreplay: run tests and replay results


*itest* [ _-eo_ ] [ _-c cflag_ ] [ _-r count_ ] [ _-v vlevel_ ] [ _-C
configfile_ ] [ _-R recordroot_ ] [ _testdir ..._ ]

*itreplay* [ _-eo_ ] [ _-v verbosity_ ] [ _recorddir ..._ ]


_Itest_ runs a sequence of tests, optionally recording all the results
in a directory tree. The _itreplay_ command replays the results of one
or more recorded tests. Some options are common to both commands:

*-e*::
  Display the standard error produced by the tests.
*-o*::
  Display the standard output produced by the tests.
**-v**__ vlevel__::
  Set the verbosity level to _vlevel_ (0-9). The higher the value, the
  more detail is displayed; the default level is 3.

The tests run by _itest_ are specified as one or more directories either
on the command line or in a configuration file. Options:

**-c**__ cflag__::
  Set the value in /dev/jit (usually 0 or 1; 0 for interpreted mode, 1
  for compiled mode) to _cflag_
**-r**__ count__::
  Run the set of tests _count_ times; a value of 0 means repeat
  indefinitely.
**-v**__ vlevel__::
  Set the verbosity level to _vlevel_ (0-9). The higher the value, the
  more detail is displayed; the default level is 3.
**-C**__ cfile__::
  Use the configuration file _cfile._ The file should contain a list of
  test directories, one per line.
**-R**__ recroot__::
  Store the test results in a tree rooted at _recroot._ Record
  directories are named as integers starting at 1. Each test run creates
  a new directory numbered one greater than the highest existing
  directory.

The test results to be replayed by _itreplay_ are specified on the
command line as one or more record directories.

=== TEST FORMAT

A test directory must contain either a t.dis file or a t.sh file,
depending on whether the test is written as a Limbo program or as a
_sh_(1) script. Limbo programs should use _itslib_(2); sh scripts should
use _sh-test_(2). A test directory should also contain a README file
(which is displayed by _itest_ if the verbosity level is greater than
8), and any other files required for the test.

Tests are run with their working directory set to their own test
directory.

=== RECORD DIRECTORY FORMAT

Each record directory contains a number of files:

*msgs*::
  All the messages generated by the test.
*stderr*::
  Standard error from the test.
*stdout*::
  Standard output from the test.
*summary*::
  a one-line file containing the start time in seconds, elapsed time in
  ms, cflag and the name of the test directory.

== SOURCE

*/appl/cmd/itest.b* +
*/appl/cmd/itreplay.b*

== SEE ALSO

_itslib_(2), _sh-test_(2)
