= mash: programmable shell


*mash* [ *-denx* ][ **-c**__command__ ] [ _file_ [ _arg ..._ ]]


_Mash_ is an older alternative to the original Inferno shell (now
_tiny_(1)). _Mash_ is a programmable shell that also allows the
definition of simple dependency rules, resembling those of Unix _make_.
It executes commands read from standard input or a file or, with the
*-c* flag, from _mash_'s argument list. Its syntax and semantics are
similar to that of Plan 9's _rc_.

=== Invocation

If _mash_ is started with no arguments it reads commands from standard
input. Otherwise its first non-flag argument is the name of a file from
which to read commands (but see *-c* below). Subsequent arguments become
the initial value of *$args*. Mash accepts the following command-line
flags.

**-c**__ string__::
  Commands are read from string.
*-d*::
  Dump parsed commands before execution.
*-e*::
  Fail if a top level command does.
*-n*::
  Parse but do not execute.
*-x*::
  Print each simple command before executing it.

If invoked without arguments _mash_ first runs the commands found in
*/lib/mashinit*.

=== Command Lines

Each command is terminated with an ampersand or a semicolon (& or ;).
When reading from */dev/cons* a newline not escaped with a backslash (\)
is treated as a semicolon. _Mash_ does not wait for a command followed
by *&* to finish executing before starting the following command.

A number-sign (#) and any following characters up to (but not including)
the next newline are ignored, except in quotation marks.

=== Simple Commands

A simple command is a sequence of words interspersed with I/O
redirections. If the first word is the name of a _mash_ function or of
one of _mash_'s built-in commands, it is executed by _mash_. Otherwise,
if the name starts with a slash (*/*), it must be the path name of a Dis
file to be loaded and executed. Names containing no initial slash are
searched for in the current directory and then in */dis*. The *.dis*
extension need not be supplied.

The keywords are

....
	case else fn for hd if in len rescue tl while 
....

=== Words and Variables

A number of constructions may be used where _mash_'s syntax requires a
word to appear. In many cases a construction's value will be a list of
strings rather than a single string.

The simplest kind of word is the unquoted word: a sequence of one or
more characters none of which is a blank, tab, newline, or any of the
following:

....
	# : ; ! ~ @ & | ^ $ = " ` ' { } ( ) < > 
....

An unquoted word that contains any of the characters ***, *?* or *[* is
a pattern for matching against file names. The character *** matches any
sequence of characters, *?* matches any single character, and *[*
_class_ *]* matches any character in the class. The class may also
contain pairs of characters separated by *-*, standing for all
characters lexically between the two. The character */* must appear
explicitly in a pattern. A pattern is replaced by a list of words, one
for each path name matched, except that a pattern matching no names is
not replaced by the empty list, but rather stands for itself. Pattern
matching is done after all other operations. Thus,

....
	x=/tmp; echo $x^/*.c; 
....

matches */tmp/*.c*, rather than matching */*.c* and then prefixing
*/tmp*.

A quoted word is a sequence of characters surrounded by single quotes
(*'*). A single quote is escaped with a backslash.

Each of the following is a word.

**$**__identifier__ +
The identifier after the *$* is the name of a variable whose value is
substituted. Variable values are lists of strings. It is an error if the
named variable has never been assigned a value.

**$**__number__ +
See the description of rules for the _mash-make_(1) builtin.

*$"* _identifier_ +
The value is a single string containing the components of the named
variable separated by spaces.

**`\{**__commands__*}* +
_mash_ executes the commands and reads the standard output, splitting it
into a list of words, using the whitespace characters (space, tab,
newline and carriage return) as separators.

*"\{* __commands__**}** +
_mash_ executes the commands and reads the standard output, splitting it
into a list of words, using the whitespace characters (space, tab,
newline and carriage return) as separators.

**<\{**__commands__*}*

**>\{**__commands__*}* +
The commands are executed asynchronously with their standard output or
standard input connected to a pipe. The value of the word is the name of
a file referring to the other end of the pipe. This allows the
construction of non-linear pipelines. For example, the following runs
two commands *old* and *new* and uses *cmp* to compare their outputs

....
	cmp <{old} <{new}; 
....

**(**__expr__*)*::
  _mash_ evaluates _expr_ as an expression. The value is a (possibly
  null) list of words. Expressions are described in detail below.

__word__**^**_word_ +
The *^* operator concatenates its two operands. If either operand is a
singleton, the concatenation is distributive. Otherwise the lists are
concatenated pairwise.

=== Free Carets

In most circumstances, _mash_ will insert the *^* operator automatically
between words that are not separated by white space. Whenever one of *$*
**'**or *`* (dollar, single quote or back quote) follows a quoted or
unquoted word or an unquoted word follows a quoted word with no
intervening blanks or tabs, a *^* is inserted between the two. If an
unquoted word immediately follows a *$* and contains a character other
than an alphanumeric, or underscore, a *^* is inserted before the first
such character. Thus

_______________________
*limbo -$flags $stem.b*
_______________________

is equivalent to

_________________________
*limbo -^$flags $stem^.b*
_________________________

=== I/O Redirections

The sequence **>**__file__ redirects the standard output file (file
descriptor 1, normally */dev/cons*) to the named _file_; **>>**__file__
appends standard output to the file. The standard input file (file
descriptor 0, also normally */dev/cons*) may be redirected from a file
by the sequence *<file*. The sequence *<>file* opens the file for
read/write and associates both file descriptor 0 and 1 with it.

== Compound Commands

A pair of commands separated by a pipe operator (*|*) is a command. The
standard output of the left command is sent through a pipe to the
standard input of the right command.

Each of the following is a command.

*if (* _expr_ *)* _command1_

*if (* _expr_ *)* _command1_ *else* _command2_ +
The _expr_ is evaluated and if the result is not null, then _command1_
is executed. In the second form _command2_ is executed if the result is
null.

*for (* _name_ *in* _list_ **)**__command__ +
The _command_ is executed once for each word in _list_ with that word
assigned to _name_.

*while (* _expr_ *)* _command_ +
The _expr_ is evaluated repeatedly until its value is null. Each time it
evaluates to non-null, the command is executed.

*case* _expr_ *\{* _pattern-list_ *=>* _command ..._ *}* +

*case* _expr-list_ *\{* _pattern_ *=>* _command ..._ *}* +
In the first form of the command the _expr_ is matched against a series
of lists of regular expressions (See _regex_(2)). The command associated
with the matching expression is executed. In the second form the
_command_ associated with the first pattern to match one of the words in
_expr-list_ is executed. An _expr-list_ will never match a
_pattern-list_.

**\{**__commands__*}*

**@\{**__commands__*}* +
Braces serve to alter the grouping of commands implied by operator
priorities. The body is a sequence of commands separated by *&* or *;*.
The second form is executed with a new scope. Either form can be
followed by redirections.

**fn**__name__**\{**__list__*}*

**fn**__name__ +
The first form defines a function with the given _name_. Subsequently,
whenever a command whose first word is _name_ is encountered, the
current value of the remainder of the command's word list will be
assigned to the local variable *args*, in a new scope, and _mash_ will
execute the list. The second form removes _name_'s function definition.

__name__**=**_list_

__name__**:=**_list_ +
The first form is an assignment to a variable. If the name is currently
defined as a local variable its value will be updated. Otherwise a
global variable with the given name will be defined or updated. The
second form is an explicit definition or update of a local variable.

__list__**:**_list_

__list__**:**__list__**\{**__commands__**}**

__word__**:~**__word__**\{**__commands__**}** +
These forms define dependencies and rules for the _make_ loadable
builtin. The first form defines a simple dependency, the second a
dependency with an explicit rule. The third form defines an implicit
rule where the left-hand word is a file pattern, the right-hand word is
the prerequisite. The right-hand word and the commands can contain
references to the characters matched by the *** meta-character in the
pattern (*$1* evaluates to the characters matched by the first ***, *$2*
the second and so on; *$0* is the entire match).

=== Expressions

Expressions evaluate to possibly null lists of strings. A word is an
expression. An expression may take one of the following forms

**(**__ expr __*)* +
Parentheses are used for grouping.

**hd**__ expr__

**tl**__ expr__

**len**__ expr__

**!**__ expr__ +
_hd_ is the first element of a list, _tl_ the remainder. _len_ is the
length of a list. Both evaluate to the null list if their operand is a
null list. *!* is the not operator and evaluates to true for a null list
or to a null list otherwise.

__expr__** ^ **_expr_

__expr__** :: **_expr_

__expr__** == **_expr_

__expr__** != **_expr_

__expr__** ~ **_expr_ +
*^* is concatenation (as defined above), *::* is list concatenation,
*==* and *!=* are the equality operators evaluating to true or the null
list, depending on the equality or inequality of the two operands. *~*
is the match operator, true if a singleton string matches one of a list
of regular expressions, or one of a list of strings matches a regular
expression. (If neither operand is a singleton it evaluates to the null
list.) *^* has the highest precedence, followed by *::* followed by the
other three. All associate to the left except *::*.

=== Built-in Commands

_Mash_ supports loadable modules of builtins. The _Mashbuiltin_ module
definition and description is in *mash.m*. One such module, _builtins_,
is loaded before _mash_ begins parsing. This module defines the
following commands

*env* +
Print global and local variables. Global variables are displayed using a
__name__**=**_value_ format, and local variables using a
__name__**:=**_value_ format.

*eval* +
Concatenate arguments and use as mash input.

*exit* +
Cause _mash_ to raise an *exit* exception.

*load* _file_ +
Load a builtin module. The _file_ must be a module with type
*Mashbuiltin*. The argument _file_ is assumed to contain a path to the
loadable module. If no such module is found then the string
*/dis/lib/mash/* is prepended to _file_ and the load is retried.

*prompt*

**prompt**__text__

**prompt**__text contin__ +
When called with no arguments causes the current value of the _mash_
prompt to be printed to standard output. The default value is *mash%*.
The second form sets a new prompt. The final form sets a new prompt and
additionally a continuation string. Initially the continuation string is
set to a single tab character. _Mash_ uses the continuation string in
place of the prompt string to indicate that the preceding line has been
continued by escaping with a final backslash (*\*) character.

**quote**__args...__ +
Print arguments quoted as input for _mash_.

**run -**__[__**denx**__] file [arg...]__ +
Interpret a file as input to _mash_.

**time**__cmd [arg...]__ +
Time the execution of a command. The total execution time is reported in
seconds and on standard error when the command completes.

**whatis**__name__ +
Print variable, function or builtin. The object given by _name_ is
described on standard output in a format that reflects its type.

The _make_ loadable builtin provides `make` functionality. The _tk_
loadable builtin provides control over some of the visual elements of a
_mash_ window.

=== Adding Builtins

New builtins can be added to _mash_ by creating a _Dis_ module that can
be loaded with a *Mashbuiltin* module interface (defined in mash.m). The
new module is loaded with the builtin *load* command which calls its
*mashinit* function to initialise it with an argument containing the
*load* command line. The function should use this call to register the
set of builtins that the module will provide using the *Env.defbuiltin*
function. Thereafter, each time one of the registered builtins is
invoked the module's *mashcmd* function is called passing as an argument
a list containing the invoked builtin name and its arguments. See the
examples in *mash/builtins.b*, *mash/make.b*, and *mash/tk.b*.

== FILES

*/lib/mashinit* +
*/dis/lib/mash*

== SOURCE

*/appl/cmd/mash*

== SEE ALSO

_mash-tk_(1), _mash-make_(1), _regex_(2)

Tom Duff, ``Rc - The Plan 9 Shell'', in the _Plan 9 Programmer's Manual
, Second Edition,_ Volume 2.
