= tail: deliver the last part of a file


*tail* [ [+-]*_number_*[lbc][*rf*] ] [ _file_ ]

*tail* [ *-fr* ] [ *-n* _nlines_ ] [ *-c* _ncharacters_ ] [ _file_ ]


_Tail_ copies the named file to the standard output beginning at a
designated place. If no file is named, the standard input is copied.

Copying begins at position **+**__number__ measured from the beginning,
or **-**__number__ from the end of the input. _Number_ is counted in
lines, 1K blocks or characters, according to the appended flag

or

Default is *-10l* (ten ell).

The further flag

causes tail to print lines from the end of the file in reverse order;

(follow) causes _tail,_ after printing to the end, to keep watch and
print further data as it appears.

The second syntax is that promulgated by POSIX, where the numbers of
lines (-n) or characters (-c) are specified separately as signed
integers. Note than an unsigned value is treated as negative, ie '-n 2'
is equivalent to '-n -2'.

== EXAMPLES

*tail file*::
  Print the last 10 lines of a file.
*tail +0f file*::
  Print a file, and continue to watch data accumulate as it grows. +
  According to custom, option **+**__number__ counts lines from 1, and
  counts blocks and characters from 0.
*tail -nlines +3 file*::
  Print a file starting at line number 3
