= unicode: interpret Unicode characters


*unicode* [ *-nt* ] __hexmin__**-**_hexmax_

*unicode* [ *-t* ] _hex ..._

*unicode* [ *-n* ] _char ..._


_Unicode_ converts between UTF and character values from the Unicode
Standard (see _utf_(6)).

If given a range of hexadecimal numbers, _unicode_ prints a table of the
specified Unicode characters including their values and UTF
representations. Otherwise, it translates from UTF to numeric value or
numeric value to UTF, depending on the appearance of the supplied text.
If converting to UTF, the characters are printed one per line.

The options are:

*-n*::
  Forces numeric output to avoid ambiguity with numeric characters.
*-t*::
  Output a single string containing the specified characters, rather
  than one per line.

The output of _unicode_ might not be helpful if the characters printed
are not available in the current font.

== EXAMPLES

*unicode p*::
  Print the hex value of *p*.
*unicode 2200-22f1*::
  Print a table of miscellaneous mathematical symbols.

== FILES

*/lib/unicode*::
  Table of characters and descriptions.

== SOURCE

*/appl/cmd/unicode.b*

== SEE ALSO

_tr_(1), _utf_(6), _font_(6)
