= xd: dump file contents in multiple formats


*xd* [ _option_ ... ] [ **-**__format__ ... ] [ _file_... ]


*Xd* dumps the contents of each _file_ in one or more formats. If no
file is specified, standard input is read. Input is processed in 16 byte
chunks. Each chunk is output in each of the specified __format__s, one
format per line. Each line of output is prefixed its file offset. This
is zero padded for the first format; subsequent formats are blank
padded. If more than one _file_ is specified, the name of each file is
output at the start of its dump.

Output formats are specified by a two character name, *4x* by default.
The first character defines the byte width of the format; the second
character defines the style of output.

The available width specifiers are:

*1* or *b*::
  1 byte units.
*2* or *w*::
  2 byte big-endian units.
*4* or *l*::
  4 byte big-endian units.
*8* or *v*::
  8 byte big-endian units.

The available styles are:

*o*::
  Octal

*d*::
  Decimal
*x*::
  Hexadecimal

In addition to the above format specifiers, *-c* can be used to denote
ASCII format. This is the same as *1x* except that codes are printed as
printable ASCII characters or Limbo escape sequences where possible.

== OPTIONS

*-u*::
  Unbuffered output. The output buffer is flushed after the dump of each
  16 byte input chunk has been generated.
*-r*::
  Mark repeated 16 byte input chunks. The first chunk is output as per
  the format specifiers, followed by an asterisk representing 1 or more
  occurrences of identical data.
*-s*::
  Reverse the order of input bytes in chunks of 4 before processing for
  output.
**-a**__style__::
  Print file addresses in the given _style_.

== SOURCE

*/appl/cmd/xd.b*::

== BUGS

There is no means of dumping 2 or 8 byte wide values in little-endian
form.
